global using BlazorComponent;
global using BlazorComponent.I18n;
global using Masa.Blazor;
global using Masa.Stack.Components.Configs;
global using Microsoft.AspNetCore.Components;
global using Microsoft.Extensions.DependencyInjection;
global using Masa.Stack.Components.Models;
global using Masa.Stack.Components.GlobalNavigations;
global using Masa.Stack.Components.GlobalUsers;